<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Basic usage' => 'Podstawowe użycie',
  'Default theme' => 'Domyślny motyw',
  'Demos' => 'Dema',
  'EDataTables' => 'EDataTables',
  'English' => 'Angielski',
  'Exporter' => 'Exporter',
  'Faker' => 'Faker',
  'Grouping' => 'Grupowanie',
  'Home' => 'Start',
  'Language' => 'Język',
  'List' => 'Lista',
  'Locale' => 'Lokalizacja',
  'Login' => 'Zaloguj się',
  'Logout' => 'Wyloguj się',
  'Notifications' => 'Powiadomienia',
  'Polish' => 'Polski',
  'Print' => 'Drukuj',
  'Profile' => 'Profil',
  'Save as CSV' => 'Zapisz jako CSV',
  'Theme' => 'Motyw',
  'Toolbar buttons' => 'Przyciski paska narzędziowego',
  'Twitter Bootstrap using yiistrap' => 'Twitter Bootstrap z użyciem yiistrap',
  '{module} module' => 'Moduł {module}',
);
