<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Activation Key' => 'Klucz aktywacyjny',
  'Code' => 'Kod',
  'Comment' => 'Komentarz',
  'Country' => 'Kraj',
  'Created On' => 'Utworzony dnia',
  'Currency' => 'Waluta',
  'Date' => 'Data',
  'Email' => 'Email',
  'Email Verified' => 'Email zweryfikowany',
  'Fifa Code' => 'Kod FIFA',
  'Fips Code' => 'Kod FIPS',
  'Firstname' => 'Imię',
  'French Short Name' => 'Krótka nazwa (po francusku)',
  'Gaul Code' => 'Kod GAUL',
  'ID' => 'ID',
  'Ioc Code' => 'Kod IOC',
  'Is Active' => 'Jest aktywny',
  'Is Disabled' => 'Jest wyłączony',
  'Is Independent' => 'Jest niezależny',
  'Itu Code' => 'Kod ITU',
  'Last Visit On' => 'Ostatnia wizyta dnia',
  'Lastname' => 'Nazwisko',
  'Marc Code' => 'Kod MARC',
  'Minor Unit' => 'Mniejsza jednostka',
  'Name' => 'Nazwa',
  'Number' => 'Numer',
  'Numeric Code' => 'Kod numeryczny',
  'Password' => 'Hasło',
  'Password Set On' => 'Hasło ustawione dnia',
  'Precious Metal' => 'Metal szlachetny',
  'Rate' => 'Kurs',
  'Short Code' => 'Krótki kod',
  'Short Name' => 'Krótka nazwa',
  'Telephone Prefix' => 'Prefiks telefoniczny',
  'Updated On' => 'Zaktualizowany dnia',
  'User' => 'Użytkownik',
  'Username' => 'Nazwa użytkownika',
  'Vehicle Code' => 'Kod pojazdu',
  'Withdrawn Date' => 'Data wycofania',
  'Wmo Code' => 'Kod WMO',
);
